# Run generate-docs script.

# TODO: push on master shimming-toolbox
trigger:
- master

# use the self-hosted runner at tristano.neuro.polymtl.ca
# this has Matlab installed and a license to use it.
pool: 'Default'

steps:

- script: |
    ./generate-docs.sh
  displayName: 'Generate and publish website'
  env:
    GH_PAGES_TOKEN: $(GH_PAGES_TOKEN)
    CUSTOM_DOMAIN: www.shimming-toolbox.org
