site_name: Shimming-toolbox
theme: {name: material}
repo_url: https://github.com/neuropoly/realtime_shimming
docs_dir: ./docs
markdown_extensions:
  - admonition
nav:
- 'Introduction': 'index.md'
- 'Getting Started': 'getting_started.md'
- 'Help': 'help.md'
- 'Contributing':
  - 'General': 'contributing.md'
  - 'API documentation':
    - 'Insert doc here': 'docs.md'
- 'Other ressources':
  - 'Hardware':
    - 'Description': 'description.md'
    - 'Assembly': 'assembly.md'
- 'Contributors': 'contributors.md'
- 'License': 'license.md'
  
